apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: dojo
  labels:
    environment: test
spec:
  containers:
    - name: server
      image: registry.redhat.io/rhscl/mysql-57-rhel7:latest
      ports:
        - containerPort: 3306
          name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Pa55w0rd"
        - name: MYSQL_USER
          value: "auser"
        - name: MYSQL_PASSWORD
          value: "pa55w0rd"
        - name: MYSQL_DATABASE
          value: "db"
      volumeMounts:
      - name: data-storage
        mountPath: /var/lib/mysql
  volumes:
  - name: data-storage
    emptyDir: {}
  restartPolicy: Never
